export enum USER_ACTION_TYPES {
	SET_CURRENT_USER_IS_AUTH = 'user/SET_CURRENT_USER_IS_AUTH',
	SET_CURRENT_USER_NAME = 'user/SET_CURRENT_USER_NAME',
	SET_CURRENT_USER_EMAIL = 'user/SET_CURRENT_USER_EMAIL',
	SET_CURRENT_USER_TOKEN = 'user/SET_CURRENT_USER_TOKEN',
	SET_CURRENT_USER_ROLE = 'user/SET_CURRENT_USER_ROLE',
	CLEAR_CURRENT_USER = 'user/CLEAR_CURRENT_USER',
	FETCH_USER_START = 'user/FETCH_USER_START',
	FETCH_USER_SUCCESS = 'user/FETCH_USER_SUCCESS',
	FETCH_USER_FAILURE = 'user/FETCH_USER_FAILURE',
}
