export enum USER_ACTION_TYPES {
	SET_CURRENT_USER_IS_AUTH = 'user/SET_CURRENT_USER_IS_AUTH',
	SET_CURRENT_USER_NAME = 'user/SET_CURRENT_USER',
	SET_CURRENT_USER_EMAIL = 'user/SET_CURRENT_USER_EMAIL',
	SET_CURRENT_USER_TOKEN = 'user/SET_CURRENT_USER_TOKEN',
}
