export enum AUTHORS_ACTION_TYPES {
	SET_AUTHORS_LIST = 'authors/SET_AUTHORS_LIST',
	ADD_AUTHOR_TO_LIST = 'authors/ADD_AUTHOR_TO_LIST',
	FETCH_AUTHORS_START = 'authors/FETCH_AUTHORS_START',
	FETCH_AUTHORS_SUCCESS = 'authors/FETCH_AUTHORS_SUCCESS',
	FETCH_AUTHORS_FAILURE = 'authors/FETCH_AUTHORS_FAILURE',
}
