export enum COURSES_ACTION_TYPES {
	SET_FILTER_FIELD = 'courses/SET_FILTER_FIELD',
	SET_COURSES_LIST = 'courses/SET_COURSES_LIST',
	ADD_NEW_COURSE_TO_LIST = 'courses/ADD_NEW_COURSE_TO_LIST',
	DELETE_COURSE_FROM_LIST = 'courses/DELETE_COURSE_FROM_LIST',
	UPDATE_COURSE_IN_LIST = 'courses/UPDATE_COURSE_IN_LIST',
}
