export const CREATE_COURSE_ACTION_TYPES = {
	SET_NOT_ADDED_AUTHORS_LIST: 'createCourse/SET_NOT_ADDED_AUTHORS_LIST',
	SET_ADDED_AUTHORS_LIST: 'createCourse/SET_ADDED_AUTHORS_LIST',
	SET_TIME_MINUTES: 'createCourse/SET_TIME_MINUTES',
	SET_TIME_HOURS: 'createCourse/SET_TIME_HOURS',
	SET_COURSE_TITLE: 'createCourse/SET_COURSE_TITLE',
	SET_COURSE_DESCRIPTION: 'createCourse/SET_COURSE_DESCRIPTION',
};
